version: '3.1'
services:
  API:
    image: 'order-service.jar'
    ports:
      - "8081:8081"
    depends_on:
      - Database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://Database:5432/order-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  Database:
    image: postgres:13.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=order-service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5